package com.platformmake.model.entity;

public class Connect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.id
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.eqid
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    private Integer eqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.proid
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connect.yield
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    private Integer yield;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.id
     *
     * @return the value of connect.id
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.id
     *
     * @param id the value for connect.id
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.eqid
     *
     * @return the value of connect.eqid
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public Integer getEqid() {
        return eqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.eqid
     *
     * @param eqid the value for connect.eqid
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public void setEqid(Integer eqid) {
        this.eqid = eqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.proid
     *
     * @return the value of connect.proid
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.proid
     *
     * @param proid the value for connect.proid
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connect.yield
     *
     * @return the value of connect.yield
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public Integer getYield() {
        return yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connect.yield
     *
     * @param yield the value for connect.yield
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    public void setYield(Integer yield) {
        this.yield = yield;
    }
}