package com.platformmake.model.entity;

public class Equipinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipinfo.eqid
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    private Integer eqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipinfo.eqstate
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    private Integer eqstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipinfo.eqpic
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    private String eqpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipinfo.eqid
     *
     * @return the value of equipinfo.eqid
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    public Integer getEqid() {
        return eqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipinfo.eqid
     *
     * @param eqid the value for equipinfo.eqid
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    public void setEqid(Integer eqid) {
        this.eqid = eqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipinfo.eqstate
     *
     * @return the value of equipinfo.eqstate
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    public Integer getEqstate() {
        return eqstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipinfo.eqstate
     *
     * @param eqstate the value for equipinfo.eqstate
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    public void setEqstate(Integer eqstate) {
        this.eqstate = eqstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipinfo.eqpic
     *
     * @return the value of equipinfo.eqpic
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    public String getEqpic() {
        return eqpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipinfo.eqpic
     *
     * @param eqpic the value for equipinfo.eqpic
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    public void setEqpic(String eqpic) {
        this.eqpic = eqpic == null ? null : eqpic.trim();
    }

	public Equipinfo() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Equipinfo(Integer eqid, Integer eqstate, String eqpic) {
		super();
		this.eqid = eqid;
		this.eqstate = eqstate;
		this.eqpic = eqpic;
	}

	@Override
	public String toString() {
		return "Equipinfo [eqid=" + eqid + ", eqstate=" + eqstate + ", eqpic=" + eqpic + "]";
	}
    
    
    
}