package com.platformmake.model.entity;

import java.util.Date;

public class Orderinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ordid
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Integer ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ordsource
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private String ordsource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.proid
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.proordnum
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Integer proordnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orddl
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Date orddl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.ordstate
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Integer ordstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.quacom
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Integer quacom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.apc
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    private Integer apc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ordid
     *
     * @return the value of orderinfo.ordid
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Integer getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ordid
     *
     * @param ordid the value for orderinfo.ordid
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setOrdid(Integer ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ordsource
     *
     * @return the value of orderinfo.ordsource
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public String getOrdsource() {
        return ordsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ordsource
     *
     * @param ordsource the value for orderinfo.ordsource
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setOrdsource(String ordsource) {
        this.ordsource = ordsource == null ? null : ordsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.proid
     *
     * @return the value of orderinfo.proid
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.proid
     *
     * @param proid the value for orderinfo.proid
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.proordnum
     *
     * @return the value of orderinfo.proordnum
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Integer getProordnum() {
        return proordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.proordnum
     *
     * @param proordnum the value for orderinfo.proordnum
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setProordnum(Integer proordnum) {
        this.proordnum = proordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orddl
     *
     * @return the value of orderinfo.orddl
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Date getOrddl() {
        return orddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orddl
     *
     * @param orddl the value for orderinfo.orddl
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setOrddl(Date orddl) {
        this.orddl = orddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.ordstate
     *
     * @return the value of orderinfo.ordstate
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Integer getOrdstate() {
        return ordstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.ordstate
     *
     * @param ordstate the value for orderinfo.ordstate
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setOrdstate(Integer ordstate) {
        this.ordstate = ordstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.quacom
     *
     * @return the value of orderinfo.quacom
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Integer getQuacom() {
        return quacom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.quacom
     *
     * @param quacom the value for orderinfo.quacom
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setQuacom(Integer quacom) {
        this.quacom = quacom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.apc
     *
     * @return the value of orderinfo.apc
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public Integer getApc() {
        return apc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.apc
     *
     * @param apc the value for orderinfo.apc
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    public void setApc(Integer apc) {
        this.apc = apc;
    }
}