package com.platformmake.model.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Planinfo {
    public Planinfo() {
		super();
		// TODO �Զ����ɵĹ��캯�����
	}


	public Planinfo(Integer planid, Integer ordid, Integer proid, Integer plancount, Date ddl, Date plansttime,
			Date planentime, Integer planstate) {
		super();
		this.planid = planid;
		this.ordid = ordid;
		this.proid = proid;
		this.plancount = plancount;
		this.ddl = ddl;
		this.plansttime = plansttime;
		this.planentime = planentime;
		this.planstate = planstate;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.planid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer planid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.ordid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.proid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.plancount
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer plancount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.ddl
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date ddl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.plansttime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date plansttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.planentime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date planentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column planinfo.planstate
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer planstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.planid
     *
     * @return the value of planinfo.planid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getPlanid() {
        return planid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.planid
     *
     * @param planid the value for planinfo.planid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setPlanid(Integer planid) {
        this.planid = planid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.ordid
     *
     * @return the value of planinfo.ordid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.ordid
     *
     * @param ordid the value for planinfo.ordid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setOrdid(Integer ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.proid
     *
     * @return the value of planinfo.proid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.proid
     *
     * @param proid the value for planinfo.proid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.plancount
     *
     * @return the value of planinfo.plancount
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getPlancount() {
        return plancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.plancount
     *
     * @param plancount the value for planinfo.plancount
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setPlancount(Integer plancount) {
        this.plancount = plancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.ddl
     *
     * @return the value of planinfo.ddl
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Date getDdl() {
        return ddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.ddl
     *
     * @param ddl the value for planinfo.ddl
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setDdl(Date ddl) {
        this.ddl = ddl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.plansttime
     *
     * @return the value of planinfo.plansttime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Date getPlansttime() {
        return plansttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.plansttime
     *
     * @param plansttime the value for planinfo.plansttime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setPlansttime(Date plansttime) {
        this.plansttime = plansttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.planentime
     *
     * @return the value of planinfo.planentime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Date getPlanentime() {
        return planentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.planentime
     *
     * @param planentime the value for planinfo.planentime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setPlanentime(Date planentime) {
        this.planentime = planentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column planinfo.planstate
     *
     * @return the value of planinfo.planstate
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getPlanstate() {
        return planstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column planinfo.planstate
     *
     * @param planstate the value for planinfo.planstate
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setPlanstate(Integer planstate) {
        this.planstate = planstate;
    }


	@Override
	public String toString() {
		return "Planinfo [planid=" + planid + ", ordid=" + ordid + ", proid=" + proid + ", plancount=" + plancount
				+ ", ddl=" + ddl + ", plansttime=" + plansttime + ", planentime=" + planentime + ", planstate="
				+ planstate + "]";
	}



}