package com.platformmake.model.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Trackinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.id
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.workid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer workid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.planid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer planid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.proid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.trackstate
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer trackstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.working_count
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer workingCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.qualified_count
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    private Integer qualifiedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.cratetime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date cratetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackinfo.uptime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date uptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.id
     *
     * @return the value of trackinfo.id
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.id
     *
     * @param id the value for trackinfo.id
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.workid
     *
     * @return the value of trackinfo.workid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.workid
     *
     * @param workid the value for trackinfo.workid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.planid
     *
     * @return the value of trackinfo.planid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getPlanid() {
        return planid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.planid
     *
     * @param planid the value for trackinfo.planid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setPlanid(Integer planid) {
        this.planid = planid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.proid
     *
     * @return the value of trackinfo.proid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.proid
     *
     * @param proid the value for trackinfo.proid
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.trackstate
     *
     * @return the value of trackinfo.trackstate
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getTrackstate() {
        return trackstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.trackstate
     *
     * @param trackstate the value for trackinfo.trackstate
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setTrackstate(Integer trackstate) {
        this.trackstate = trackstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.working_count
     *
     * @return the value of trackinfo.working_count
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getWorkingCount() {
        return workingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.working_count
     *
     * @param workingCount the value for trackinfo.working_count
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setWorkingCount(Integer workingCount) {
        this.workingCount = workingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.qualified_count
     *
     * @return the value of trackinfo.qualified_count
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Integer getQualifiedCount() {
        return qualifiedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.qualified_count
     *
     * @param qualifiedCount the value for trackinfo.qualified_count
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setQualifiedCount(Integer qualifiedCount) {
        this.qualifiedCount = qualifiedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.cratetime
     *
     * @return the value of trackinfo.cratetime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Date getCratetime() {
        return cratetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.cratetime
     *
     * @param cratetime the value for trackinfo.cratetime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setCratetime(Date cratetime) {
        this.cratetime = cratetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackinfo.uptime
     *
     * @return the value of trackinfo.uptime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackinfo.uptime
     *
     * @param uptime the value for trackinfo.uptime
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

	@Override
	public String toString() {
		return "Trackinfo [id=" + id + ", workid=" + workid + ", planid=" + planid + ", proid=" + proid
				+ ", trackstate=" + trackstate + ", workingCount=" + workingCount + ", qualifiedCount=" + qualifiedCount
				+ ", cratetime=" + cratetime + ", uptime=" + uptime + "]";
	}

	public Trackinfo(Integer id, Integer workid, Integer planid, Integer proid, Integer trackstate,
			Integer workingCount, Integer qualifiedCount, Date cratetime, Date uptime) {
		super();
		this.id = id;
		this.workid = workid;
		this.planid = planid;
		this.proid = proid;
		this.trackstate = trackstate;
		this.workingCount = workingCount;
		this.qualifiedCount = qualifiedCount;
		this.cratetime = cratetime;
		this.uptime = uptime;
	}

	public Trackinfo() {
		super();
		// TODO 自动生成的构造函数存根
	}
}