package com.platformmake.model.dao;

import com.platformmake.model.entity.Connect;
import com.platformmake.model.entity.ConnectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConnectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    long countByExample(ConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int deleteByExample(ConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int insert(Connect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int insertSelective(Connect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    List<Connect> selectByExample(ConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    Connect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") Connect record, @Param("example") ConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int updateByExample(@Param("record") Connect record, @Param("example") ConnectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int updateByPrimaryKeySelective(Connect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect
     *
     * @mbg.generated Thu Jul 23 10:55:04 CST 2020
     */
    int updateByPrimaryKey(Connect record);
}