package com.platformmake.model.dao;

import com.platformmake.model.entity.DayWork;
import com.platformmake.model.entity.DayWorkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    long countByExample(DayWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int deleteByExample(DayWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int insert(DayWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int insertSelective(DayWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    List<DayWork> selectByExample(DayWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    DayWork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") DayWork record, @Param("example") DayWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByExample(@Param("record") DayWork record, @Param("example") DayWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(DayWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_work
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByPrimaryKey(DayWork record);
}