package com.platformmake.model.dao;

import com.platformmake.model.entity.Equipinfo;
import com.platformmake.model.entity.EquipinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    long countByExample(EquipinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int deleteByExample(EquipinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int deleteByPrimaryKey(Integer eqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int insert(Equipinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int insertSelective(Equipinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    List<Equipinfo> selectByExample(EquipinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    Equipinfo selectByPrimaryKey(Integer eqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") Equipinfo record, @Param("example") EquipinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int updateByExample(@Param("record") Equipinfo record, @Param("example") EquipinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int updateByPrimaryKeySelective(Equipinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipinfo
     *
     * @mbg.generated Thu Jul 23 15:33:19 CST 2020
     */
    int updateByPrimaryKey(Equipinfo record);
    
    int statisticsEq(@Param("eqstate") Integer eqstate);
}