package com.platformmake.model.dao;

import com.platformmake.model.entity.Orderinfo;
import com.platformmake.model.entity.OrderinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    long countByExample(OrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int deleteByExample(OrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int deleteByPrimaryKey(Integer ordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int insert(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int insertSelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    List<Orderinfo> selectByExample(OrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    Orderinfo selectByPrimaryKey(Integer ordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Orderinfo record, @Param("example") OrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int updateByExample(@Param("record") Orderinfo record, @Param("example") OrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int updateByPrimaryKeySelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Fri Jul 24 19:21:12 CST 2020
     */
    int updateByPrimaryKey(Orderinfo record);
}