package com.platformmake.model.dao;

import com.platformmake.model.entity.Productinfo;
import com.platformmake.model.entity.ProductinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    long countByExample(ProductinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int deleteByExample(ProductinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int deleteByPrimaryKey(Integer proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int insert(Productinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int insertSelective(Productinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    List<Productinfo> selectByExample(ProductinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    Productinfo selectByPrimaryKey(Integer proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") Productinfo record, @Param("example") ProductinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int updateByExample(@Param("record") Productinfo record, @Param("example") ProductinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int updateByPrimaryKeySelective(Productinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productinfo
     *
     * @mbg.generated Thu Jul 23 10:17:05 CST 2020
     */
    int updateByPrimaryKey(Productinfo record);
}