package com.platformmake.model.dao;

import com.platformmake.model.entity.Trackinfo;
import com.platformmake.model.entity.TrackinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrackinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    long countByExample(TrackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int deleteByExample(TrackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int insert(Trackinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int insertSelective(Trackinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    List<Trackinfo> selectByExample(TrackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    Trackinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") Trackinfo record, @Param("example") TrackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByExample(@Param("record") Trackinfo record, @Param("example") TrackinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByPrimaryKeySelective(Trackinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trackinfo
     *
     * @mbg.generated Sun Jul 26 23:40:19 CST 2020
     */
    int updateByPrimaryKey(Trackinfo record);
}